// search-index.js
const searchIndex = [
  {
    id: "home",
    title: "Home",
    content: "Understanding the Cosmos - Educational space portal",
    url: "index.html",
    category: "Home",
  },

  {
    id: "galaxy-types",
    title: "Types of Galaxies",
    content:
      "Elliptical Galaxies, Spiral Galaxies, Barred Spirals, Lenticular Galaxies, Irregular Galaxies, Active Galaxies, Interacting Galaxies, Peculiar Galaxies",
    url: "index.html#section1",
    category: "Galaxies",
  },  
  {
    id: "elliptical",
    title: "Elliptical Galaxies",
    content: "E0, E1, E2-E7, Dwarf Ellipticals, Brightest Cluster Galaxies",
    url: "index.html#section1",
    category: "Galaxies",
  },
  {
    id: "spiral",
    title: "Spiral Galaxies",
    content: "Sa, Sb, Sc types including Andromeda, Whirlpool, Triangulum",
    url: "index.html#section1",
    category: "Galaxies",
  },
  {
    id: "milky-way",
    title: "Milky Way",
    content: "Our home galaxy, barred spiral galaxy",
    url: "index.html#section1",
    category: "Galaxies",
  },

  {
    id: "space-objects",
    title: "Types of Objects in Space",
    content:
      "Stars, Planets, Nebulae, Galaxies, Active Objects, Cosmological structures",
    url: "index.html#section1",
    category: "Astronomy",
  },
  {
    id: "stars",
    title: "Stars",
    content:
      "O, B, A, F, G, K, M types, Protostars, Giants, White Dwarfs, Neutron Stars, Black holes",
    url: "index.html#section1",
    category: "Stars",
  },
  {
    id: "nebulae",
    title: "Nebulae",
    content:
      "Emission Nebulae, Reflection, Dark Nebulae, Planetary Nebulas, Supernova Remnants",
    url: "index.html#section1",
    category: "Nebulae",
  },

  {
    id: "star-catalog",
    title: "HYG Star Catalog",
    content: "Hipparcos, Yale Bright Star, and Gliese catalogs merged dataset",
    url: "index.html#section1",
    category: "Data",
  },

  {
    id: "andromeda",
    title: "Andromeda Galaxy",
    content: "M31, nearest spiral galaxy to Milky Way",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "pillars",
    title: "Pillars of Creation",
    content: "Eagle Nebula M16, iconic star-forming region",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "crab-nebula",
    title: "Crab Nebula",
    content: "Messier 1, supernova remnant",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "Sombrero-galaxy",
    title: "Sombrero Galaxy",
    content: "M104, edge-on spiral galaxy",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "Lunar-Eclipse",
    title: "Lunar Eclipse",
    content: "Lunar Eclipse, A event in the solar system",
    url: "1.42-lunar-eclipse.html",
    category: "Gallery",
  },
  {
    id: "Solar-Eclipse",
    title: "Solar Eclipse",
    content: "Solar Eclipse, A event in the solar system",
    url: "1.41-solar-eclipse.html",
    category: "Solar Eclipse",
  },
  {
    id: "mercury",
    title: "Mercury",
    content: "Closest planet to the Sun; small, rocky, extreme temperature variations",
    url: "2.0-index.html",
    category: "Planets",
  },
  {
    id: "venus",
    title: "Venus",
    content: "Second planet from the Sun; dense atmosphere and runaway greenhouse effect",
    url: "2.0-index.html",
    category: "Planets",
  },
  {
    id: "earth",
    title: "Earth",
    content: "Our home planet; liquid water, life-bearing, complex climate systems",
    url: "2.0-index.html",
    category: "Planets",
  },
  {
    id: "mars",
    title: "Mars",
    content: "The Red Planet; evidence of past water, current robotic exploration",
    url: "2.0-index.html",
    category: "Planets",
  },
  {
    id: "jupiter",
    title: "Jupiter",
    content: "Gas giant with a strong magnetic field and the Great Red Spot storm",
    url: "2.0-index.html",
    category: "Planets",
  },
  {
    id: "saturn",
    title: "Saturn",
    content: "Ringed gas giant known for its extensive ring system and many moons",
    url: "2.0-index.html",
    category: "Planets",
  },
  {
    id: "uranus",
    title: "Uranus",
    content: "Ice giant with a tilted rotation axis, faint ring system",
    url: "2.0-index.html",
    category: "Planets",
  },
  {
    id: "neptune",
    title: "Neptune",
    content: "Distant ice giant with strong winds and dynamic weather patterns",
    url: "2.0-index.html",
    category: "Planets",  
  },
  {
    id: "asteroids",
    title: "Asteroids and Minor Bodies",
    content: "Small rocky bodies, main belt, near-Earth objects and Trojan asteroids",
    url: "2.0-index.html",
    category: "Small Bodies",
  },
  {
    id: "exoplanets",
    title: "Exoplanets",
    content: "Planets orbiting other stars; detection methods and notable discoveries",
    url: "1.72-Exoplanets.html",
    category: "Exoplanets",
  },
  {
    id: "neutron-stars",
    title: "Neutron Stars",
    content: "Collapsed cores of massive stars; pulsars and magnetars included",
    url: "1.73-Neutron-stars.html",
    category: "Stars",
  },
  {
    id: "black-holes",
    title: "Black Holes",
    content: "Regions of extreme gravity, from stellar-mass to supermassive black holes",
    url: "1.74-Blackholes.html",
    category: "Cosmology",
  },
  {
    id: "nebulas-page",
    title: "Nebulas Overview",
    content: "Clouds of gas and dust where stars are born and supernova remnants remain",
    url: "1.75-Nebulas.html",
    category: "Nebulae",
  },
  {
    id: "galaxies-overview",
    title: "Galaxies Overview",
    content: "Structures of stars, gas, dust, dark matter; classifications and examples",
    url: "1.76-Galaxies.html",
    category: "Galaxies",
  },
  {
    id: "kuiper-belt",
    title: "Kuiper Belt",
    content: "Region beyond Neptune populated by icy bodies and dwarf planets",
    url: "Kuiper-belt.html",
    category: "Solar System",
  },
  {
    id: "comets",
    title: "Comets",
    content: "Icy bodies that develop tails when approaching the Sun; periodic and long-period comets",
    url: "Comets.html",
    category: "Small Bodies",
  },
  {
    id: "meteor-shower",
    title: "Meteor Shower",
    content: "Streams of meteoroids producing yearly meteor showers like Perseids and Leonids",
    url: "1.44-meteor-shower.html",
    category: "Events",
  },
  {
    id: "satellites",
    title: "Satellites",
    content: "Human-made satellites and observational platforms orbiting Earth and beyond",
    url: "1.61-Satellites.html",
    category: "Missions",
  },
  {
    id: "constellations",
    title: "Constellations",
    content: "Patterns of stars used for navigation and storytelling across cultures",
    url: "2.01-Constellation.html",
    category: "Sky",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { searchIndex };
}
