// search-index.js
const searchIndex = [
  {
    id: "home",
    title: "Home",
    content: "Understanding the Cosmos - Educational space portal",
    url: "index.html",
    category: "Home",
  },

  {
    id: "galaxy-types",
    title: "Types of Galaxies",
    content:
      "Elliptical Galaxies, Spiral Galaxies, Barred Spirals, Lenticular Galaxies, Irregular Galaxies, Active Galaxies, Interacting Galaxies, Peculiar Galaxies",
    url: "index.html#section1",
    category: "Galaxies",
  },  
  {
    id: "elliptical",
    title: "Elliptical Galaxies",
    content: "E0, E1, E2-E7, Dwarf Ellipticals, Brightest Cluster Galaxies",
    url: "index.html#section1",
    category: "Galaxies",
  },
  {
    id: "spiral",
    title: "Spiral Galaxies",
    content: "Sa, Sb, Sc types including Andromeda, Whirlpool, Triangulum",
    url: "index.html#section1",
    category: "Galaxies",
  },
  {
    id: "milky-way",
    title: "Milky Way",
    content: "Our home galaxy, barred spiral galaxy",
    url: "index.html#section1",
    category: "Galaxies",
  },

  {
    id: "space-objects",
    title: "Types of Objects in Space",
    content:
      "Stars, Planets, Nebulae, Galaxies, Active Objects, Cosmological structures",
    url: "index.html#section1",
    category: "Astronomy",
  },
  {
    id: "stars",
    title: "Stars",
    content:
      "O, B, A, F, G, K, M types, Protostars, Giants, White Dwarfs, Neutron Stars, Black holes",
    url: "index.html#section1",
    category: "Stars",
  },
  {
    id: "nebulae",
    title: "Nebulae",
    content:
      "Emission Nebulae, Reflection, Dark Nebulae, Planetary Nebulas, Supernova Remnants",
    url: "index.html#section1",
    category: "Nebulae",
  },

  {
    id: "star-catalog",
    title: "HYG Star Catalog",
    content: "Hipparcos, Yale Bright Star, and Gliese catalogs merged dataset",
    url: "index.html#section1",
    category: "Data",
  },

  {
    id: "andromeda",
    title: "Andromeda Galaxy",
    content: "M31, nearest spiral galaxy to Milky Way",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "pillars",
    title: "Pillars of Creation",
    content: "Eagle Nebula M16, iconic star-forming region",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "crab-nebula",
    title: "Crab Nebula",
    content: "Messier 1, supernova remnant",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "Sombrero-galaxy",
    title: "Sombrero Galaxy",
    content: "M104, edge-on spiral galaxy",
    url: "1.2-gallery.html",
    category: "Gallery",
  },
  {
    id: "Lunar-Eclipse",
    title: "Lunar Eclipse",
    content: "Lunar Eclipse, A event in the solar system",
    url: "1.42-lunar-eclipse.html",
    category: "Gallery",
  },
  {
    id: "Solar-Eclipse",
    title: "Solar Eclipse",
    content: "Solar Eclipse, A event in the solar system",
    url: "1.41-solar-eclipse.html",
    category: "Solar Eclipse",
  },
  {
    id: "mercury",
    title: "Mercury",
    content: "Closest planet to the Sun; small, rocky, extreme temperature variations",
    url: "index.html",
    category: "Planets",
  },
  {
    id: "venus",
    title: "Venus",
    content: "Second planet from the Sun; dense atmosphere and runaway greenhouse effect",
    url: "index.html",
    category: "Planets",
  },
  {
    id: "earth",
    title: "Earth",
    content: "Our home planet; liquid water, life-bearing, complex climate systems",
    url: "index.html",
    category: "Planets",
  },
  {
    id: "mars",
    title: "Mars",
    content: "The Red Planet; evidence of past water, current robotic exploration",
    url: "index.html",
    category: "Planets",
  },
  {
    id: "jupiter",
    title: "Jupiter",
    content: "Gas giant with a strong magnetic field and the Great Red Spot storm",
    url: "index.html",
    category: "Planets",
  },
  {
    id: "saturn",
    title: "Saturn",
    content: "Ringed gas giant known for its extensive ring system and many moons",
    url: "index.html",
    category: "Planets",
  },
  {
    id: "uranus",
    title: "Uranus",
    content: "Ice giant with a tilted rotation axis, faint ring system",
    url: "index.html",
    category: "Planets",
  },
  {
    id: "neptune",
    title: "Neptune",
    content: "Distant ice giant with strong winds and dynamic weather patterns",
    url: "index.html",
    category: "Planets",  
  },
  {
    id: "asteroids",
    title: "Asteroids and Minor Bodies",
    content: "Small rocky bodies, main belt, near-Earth objects and Trojan asteroids",
    url: "index.html",
    category: "Small Bodies",
  },
  {
    id: "exoplanets",
    title: "Exoplanets",
    content: "Planets orbiting other stars; detection methods and notable discoveries",
    url: "1.72-Exoplanets.html",
    category: "Exoplanets",
  },
  {
    id: "neutron-stars",
    title: "Neutron Stars",
    content: "Collapsed cores of massive stars; pulsars and magnetars included",
    url: "1.73-Neutron-stars.html",
    category: "Stars",
  },
  {
    id: "black-holes",
    title: "Black Holes",
    content: "Regions of extreme gravity, from stellar-mass to supermassive black holes",
    url: "1.74-Blackholes.html",
    category: "Cosmology",
  },
  {
    id: "nebulas-page",
    title: "Nebulas Overview",
    content: "Clouds of gas and dust where stars are born and supernova remnants remain",
    url: "1.75-Nebulas.html",
    category: "Nebulae",
  },
  {
    id: "galaxies-overview",
    title: "Galaxies Overview",
    content: "Structures of stars, gas, dust, dark matter; classifications and examples",
    url: "1.76-Galaxies.html",
    category: "Galaxies",
  },
  {
    id: "kuiper-belt",
    title: "Kuiper Belt",
    content: "Region beyond Neptune populated by icy bodies and dwarf planets",
    url: "Kuiper-belt.html",
    category: "Solar System",
  },
  {
    id: "comets",
    title: "Comets",
    content: "Icy bodies that develop tails when approaching the Sun; periodic and long-period comets",
    url: "Comets.html",
    category: "Small Bodies",
  },
  {
    id: "meteor-shower",
    title: "Meteor Shower",
    content: "Streams of meteoroids producing yearly meteor showers like Perseids and Leonids",
    url: "1.44-meteor-shower.html",
    category: "Events",
  },
  {
    id: "satellites",
    title: "Satellites",
    content: "Human-made satellites and observational platforms orbiting Earth and beyond",
    url: "1.61-Satellites.html",
    category: "Missions",
  },
  {
    id: "constellations",
    title: "Constellations",
    content: "Patterns of stars used for navigation and storytelling across cultures",
    url: "2.01-Constellation.html",
    category: "Sky",
  },
  {
    id: "andromeda-galaxy",
    title: "Andromeda Galaxy",
    content: "M31, our closest major galactic neighbor",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "m31",
    title: "Andromeda Galaxy (M31)",
    content: "Spiral galaxy approaching the Milky Way",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "triangulum-galaxy",
    title: "Triangulum Galaxy (M33)",
    content: "Third-largest galaxy in Local Group",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "sunflower-galaxy",
    title: "Sunflower Galaxy (M63)",
    content: "Flocculent spiral galaxy in Canes Venatici",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "leo-triplet",
    title: "M65 & M66",
    content: "Part of the Leo Triplet galaxies",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "bodes-galaxy",
    title: "Bode's Galaxy (M81)",
    content: "Grand design spiral galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "cigar-galaxy",
    title: "Cigar Galaxy (M82)",
    content: "Starburst galaxy with intense star formation",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "southern-pinwheel",
    title: "Southern Pinwheel (M83)",
    content: "Barred spiral galaxy with supernovae",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "crocs-eye-galaxy",
    title: "Croc's Eye Galaxy (M94)",
    content: "Starburst galaxy with inner ring",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "m96-galaxy",
    title: "Messier 96 (M96)",
    content: "Double-barred spiral galaxy in Leo",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "m100-galaxy",
    title: "Messier 100 (M100)",
    content: "Perfect face-on spiral galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "pinwheel-galaxy",
    title: "Pinwheel Galaxy (M101)",
    content: "Face-on spiral galaxy in Ursa Major",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "m106-galaxy",
    title: "Messier 106 (M106)",
    content: "Spiral galaxy with active nucleus",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "sombrero-galaxy",
    title: "Sombrero Galaxy (M104)",
    content: "Edge-on spiral galaxy with large bulge",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "centaurus-a",
    title: "Centaurus A (NGC 5128)",
    content: "Radio galaxy with prominent dust lane",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-891",
    title: "NGC 891",
    content: "Edge-on spiral galaxy in Andromeda",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-1140",
    title: "NGC 1140",
    content: "Starburst dwarf galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "perseus-a",
    title: "NGC 1275 (Perseus A)",
    content: "Central galaxy of Perseus Cluster",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-1300",
    title: "NGC 1300",
    content: "Barred spiral galaxy with grand design",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-1512-1510",
    title: "NGC 1512 & NGC 1510",
    content: "Interacting galaxy pair",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "spanish-dancer",
    title: "Spanish Dancer Galaxy (NGC 1566)",
    content: "Grand design spiral galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-1672",
    title: "NGC 1672",
    content: "Barred spiral with starburst regions",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "m110",
    title: "Messier 110 (NGC 205)",
    content: "Dwarf elliptical satellite of Andromeda",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-2525",
    title: "NGC 2525",
    content: "Barred spiral galaxy in Puppis",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-3256",
    title: "NGC 3256",
    content: "Starburst galaxy from galactic merger",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-3489",
    title: "NGC 3489",
    content: "Lenticular galaxy in Leo",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "spindle-galaxy",
    title: "Spindle Galaxy (NGC 5866)",
    content: "Lenticular galaxy in Draco",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-6217",
    title: "NGC 6217",
    content: "Barred spiral galaxy in Ursa Minor",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-6240",
    title: "NGC 6240",
    content: "Ultraluminous merging galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-6340",
    title: "NGC 6340",
    content: "Lenticular galaxy in Draco",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-7049",
    title: "NGC 7049",
    content: "Lenticular galaxy with dust rings",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ngc-7714",
    title: "NGC 7714",
    content: "Starburst galaxy in Pisces",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ic-1101",
    title: "IC 1101",
    content: "One of the largest known galaxies",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ic-1613",
    title: "IC 1613",
    content: "Dwarf irregular galaxy in Cetus",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "coddingtons-nebula",
    title: "IC 2574 (Coddington's Nebula)",
    content: "Dwarf spiral galaxy in Ursa Major",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "malin-1",
    title: "Malin 1",
    content: "Giant low-surface-brightness galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "eso-510-g13",
    title: "ESO 510-G13",
    content: "Warped spiral galaxy in Hydra",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "large-magellanic-cloud",
    title: "Large Magellanic Cloud (LMC)",
    content: "Dwarf galaxy satellite of Milky Way",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "small-magellanic-cloud",
    title: "Small Magellanic Cloud (SMC)",
    content: "Dwarf galaxy near Milky Way",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "abell-2218",
    title: "Abell 2218",
    content: "Galaxy cluster with gravitational lensing",
    url: "1.2-gallery.html",
    category: "Galaxy Clusters",
},
{
    id: "pandoras-cluster",
    title: "Pandora's Cluster (Abell 2744)",
    content: "Giant galaxy cluster with multiple mergers",
    url: "1.2-gallery.html",
    category: "Galaxy Clusters",
},
{
    id: "stephens-quintet",
    title: "Stephan's Quintet (HCG 92)",
    content: "Compact group of interacting galaxies",
    url: "1.2-gallery.html",
    category: "Galaxy Clusters",
},
{
    id: "macs-j0416",
    title: "MACS J0416.1-2403",
    content: "Galaxy cluster with dark matter mapping",
    url: "1.2-gallery.html",
    category: "Galaxy Clusters",
},
{
    id: "molten-ring",
    title: "The Molten Ring (GAL-CLUS-022058s)",
    content: "Einstein ring gravitational lens",
    url: "1.2-gallery.html",
    category: "Galaxy Clusters",
},
{
    id: "tadpole-galaxy",
    title: "Tadpole Galaxy (Arp 188)",
    content: "Distorted galaxy with long tidal tail",
    url: "1.2-gallery.html",
    category: "Peculiar Galaxies",
},
{
    id: "polar-ring-galaxy",
    title: "Polar Ring Galaxy (NGC 660)",
    content: "Rare galaxy with ring perpendicular to plane",
    url: "1.2-gallery.html",
    category: "Peculiar Galaxies",
},
{
    id: "pgc-39058",
    title: "PGC 39058",
    content: "Dwarf galaxy in Draco",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ugc-4459",
    title: "UGC 4459",
    content: "Dwarf irregular galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "ugc-4879",
    title: "UGC 4879 (VV124)",
    content: "Isolated dwarf galaxy",
    url: "1.2-gallery.html",
    category: "Galaxies",
},
{
    id: "crab-nebula",
    title: "Crab Nebula (M1)",
    content: "Supernova remnant from 1054 AD",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "dumbbell-nebula",
    title: "Dumbbell Nebula (M27)",
    content: "Planetary nebula in Vulpecula",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "helix-nebula",
    title: "Helix Nebula (NGC 7293)",
    content: "Planetary nebula in Aquarius",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "red-spider-nebula",
    title: "Red Spider Nebula",
    content: "Planetary nebula with symmetric lobes",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "twin-jet-nebula",
    title: "Twin Jet Nebula (M2-9)",
    content: "Bipolar planetary nebula",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "ngc-7027",
    title: "NGC 7027",
    content: "Young planetary nebula in Cygnus",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "egg-nebula",
    title: "The Egg Nebula (CRL 2688)",
    content: "Prototypical bipolar nebula",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "blue-ring-nebula",
    title: "Blue Ring Nebula",
    content: "Rare ultraviolet nebula",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "hinds-variable-nebula",
    title: "Hind's Variable Nebula (NGC 1555)",
    content: "Variable nebula illuminated by T Tauri star",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "ant-nebula",
    title: "Ant Nebula (Mz 3)",
    content: "Bipolar planetary nebula",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "eagle-nebula",
    title: "Eagle Nebula (M16)",
    content: "Star-forming region with Pillars of Creation",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "lagoon-nebula",
    title: "Lagoon Nebula (M8)",
    content: "Giant interstellar cloud in Sagittarius",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "monkey-nebula",
    title: "Monkey Head Nebula (NGC 2174)",
    content: "Emission nebula in Orion",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "peony-nebula",
    title: "Peony Nebula",
    content: "Bright emission nebula in Milky Way",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "seagull-nebula",
    title: "Seagull Nebula (IC 2177)",
    content: "Emission nebula shaped like a bird",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "soul-nebula",
    title: "Soul Nebula (IC 1848)",
    content: "Emission nebula in Cassiopeia",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "spider-nebula",
    title: "Spider Nebula (IC 417)",
    content: "Emission nebula with star cluster",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "tarantula-nebula",
    title: "Tarantula Nebula (30 Doradus)",
    content: "Largest known star-forming region in Local Group",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "ctb-1",
    title: "CTB 1",
    content: "Supernova remnant in Cassiopeia",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "dem-l316a",
    title: "DEM L316A",
    content: "Supernova remnant in Large Magellanic Cloud",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "ldn-1622",
    title: "LDN 1622",
    content: "Dark nebula in Orion",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "iris-nebula",
    title: "Iris Nebula (NGC 7023)",
    content: "Reflection nebula in Cepheus",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "jellyfish-nebula",
    title: "Jellyfish Nebula (IC 443)",
    content: "Supernova remnant in Gemini",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "snr-b0519",
    title: "SNR B0519-69.0",
    content: "Supernova remnant in Large Magellanic Cloud",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "ngc-1333",
    title: "NGC 1333",
    content: "Reflection nebula with young stars",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "pleiades",
    title: "Pleiades (M45)",
    content: "Open star cluster in Taurus",
    url: "1.2-gallery.html",
    category: "Star Clusters",
},
{
    id: "m78",
    title: "M78",
    content: "Reflection nebula with star cluster",
    url: "1.2-gallery.html",
    category: "Nebulae",
},
{
    id: "westerlund-2",
    title: "Westerlund 2",
    content: "Young star cluster in Carina",
    url: "1.2-gallery.html",
    category: "Star Clusters",
},
{
    id: "r136",
    title: "R136",
    content: "Massive star cluster in Tarantula Nebula",
    url: "1.2-gallery.html",
    category: "Star Clusters",
},
{
    id: "b93",
    title: "B93",
    content: "Star cluster or nebula in Milky Way",
    url: "1.2-gallery.html",
    category: "Star Clusters",
},
{
    id: "blazars",
    title: "Blazars",
    content: "Active galactic nuclei with relativistic jets",
    url: "1.2-gallery.html",
    category: "Quasars",
},
{
    id: "quasars",
    title: "Quasars",
    content: "Distant active galactic nuclei",
    url: "1.2-gallery.html",
    category: "Quasars",
},
{
    id: "ulas-j1120",
    title: "ULAS J1120+0641",
    content: "Distant quasar from early universe",
    url: "1.2-gallery.html",
    category: "Quasars",
},
{
    id: "j0454",
    title: "J04542829-66252",
    content: "Deep space object designation",
    url: "1.2-gallery.html",
    category: "Astronomy",
},
{
    id: "home",
    title: "Home",
    content: "Main page of Astronomy Hub",
    url: "index.html",
    category: "Main",
},
{
    id: "about",
    title: "About",
    content: "Learn about this astronomy website",
    url: "1.1-about.html",
    category: "Main",
},
{
    id: "gallery",
    title: "Gallery",
    content: "Collection of astronomy images",
    url: "1.2-gallery.html",
    category: "Main",
},
{
    id: "resources",
    title: "Resources",
    content: "Astronomy learning resources and links",
    url: "1.3-resources.html",
    category: "Main",
},
{
    id: "news",
    title: "News",
    content: "Latest astronomy news and discoveries",
    url: "1.4-news.html",
    category: "Main",
},
{
    id: "education-main",
    title: "Education",
    content: "Main education page for astronomy",
    url: "1.90-Education-main.html",
    category: "Education",
},
{
    id: "astronomy-edu",
    title: "Astronomy Education",
    content: "Learn about astronomy fundamentals",
    url: "1.91-astronomy-edu.html",
    category: "Education",
},
{
    id: "cosmology-edu",
    title: "Cosmology Education",
    content: "Study the origin and evolution of the universe",
    url: "1.92-cosmology-edu.html",
    category: "Education",
},
{
    id: "physics",
    title: "Astrophysics",
    content: "Learn about the physics of space",
    url: "1.93-physics.html",
    category: "Education",
},
{
    id: "seti",
    title: "Extraterrestrial Life (SETI)",
    content: "Search for extraterrestrial intelligence",
    url: "1.94-Extraterrestrial-life.html",
    category: "Education",
},
{
    id: "exoplanet-detect",
    title: "Exoplanet Detection Methods",
    content: "Learn how space agencies detect exoplanets",
    url: "1.95-Exoplanet-detect.html",
    category: "Education",
},
{
    id: "solar-system",
    title: "Solar System",
    content: "Explore our solar system",
    url: "1.51-Solar-System.html",
    category: "Explore",
},
{
    id: "milky-way",
    title: "Milky Way",
    content: "Explore our home galaxy",
    url: "1.52-Milky way.html",
    category: "Explore",
},
{
    id: "local-group",
    title: "Local Group",
    content: "Explore galaxies in our local group",
    url: "1.53-Local-group.html",
    category: "Explore",
},
{
    id: "virgo-cluster",
    title: "Virgo Cluster",
    content: "Explore the Virgo galaxy cluster",
    url: "1.54-Virgo.html",
    category: "Explore",
},
{
    id: "laniakea",
    title: "Laniakea Supercluster",
    content: "Explore our home supercluster",
    url: "1.55-Laniakea.html",
    category: "Explore",
},
{
    id: "observable-universe",
    title: "Observable Universe",
    content: "Explore everything we can see",
    url: "1.56-Observable-universe.html",
    category: "Explore",
},
{
    id: "real-universe",
    title: "Real Universe",
    content: "Beyond the observable universe",
    url: "1.57-Real-universe.html",
    category: "Explore",
},
{
    id: "stars",
    title: "Stars",
    content: "Learn about different types of stars",
    url: "1.71-Stars.html",
    category: "Discover",
},
{
    id: "exoplanets",
    title: "Exoplanets",
    content: "Discover planets beyond our solar system",
    url: "1.72-Exoplanets.html",
    category: "Discover",
},
{
    id: "neutron-stars",
    title: "Neutron Stars",
    content: "Learn about these dense stellar remnants",
    url: "1.73-Neutron-stars.html",
    category: "Discover",
},
{
    id: "blackholes",
    title: "Black Holes",
    content: "Explore these mysterious objects",
    url: "1.74-Blackholes.html",
    category: "Discover",
},
{
    id: "nebulas",
    title: "Nebulas",
    content: "Discover beautiful cosmic clouds",
    url: "1.75-Nebulas.html",
    category: "Discover",
},
{
    id: "galaxies",
    title: "Galaxies",
    content: "Learn about island universes",
    url: "1.76-Galaxies.html",
    category: "Discover",
},
{
    id: "clusters",
    title: "Galaxy Clusters",
    content: "Explore groups of galaxies",
    url: "1.77-Cluster.html",
    category: "Discover",
},
{
    id: "superclusters",
    title: "Superclusters",
    content: "Learn about the largest cosmic structures",
    url: "1.78-Supercluster.html",
    category: "Discover",
},
{
    id: "walls-filaments",
    title: "Walls and Filaments",
    content: "Explore the cosmic web",
    url: "1.79-Walls-filaments.html",
    category: "Discover",
},
{
    id: "superstructures",
    title: "Superstructures",
    content: "Learn about the largest known structures",
    url: "1.791-Superstructures.html",
    category: "Discover",
},
{
    id: "blazars-quasars",
    title: "Blazars & Quasars",
    content: "Discover these powerful active galaxies",
    url: "1.792-Blazars-Quasars.html",
    category: "Discover",
},
{
    id: "telescopes",
    title: "Space Telescopes",
    content: "Learn about telescopes in space",
    url: "1.61-telescopes.html",
    category: "Missions",
},
{
    id: "observatories",
    title: "Observatories",
    content: "Explore ground-based astronomy facilities",
    url: "1.62-observatories.html",
    category: "Missions",
},
{
    id: "rovers",
    title: "Rovers & Atmospheric Probes",
    content: "Discover robots exploring other worlds",
    url: "1.63 Rovers.html",
    category: "Missions",
},
{
    id: "satellites",
    title: "Satellites",
    content: "Learn about satellites orbiting Earth",
    url: "1.64-Satellites.html",
    category: "Missions",
},
{
    id: "solar-eclipse",
    title: "Solar Eclipse",
    content: "Learn about solar eclipses",
    url: "1.41-solar-eclipse.html",
    category: "Events",
},
{
    id: "lunar-eclipse",
    title: "Lunar Eclipse",
    content: "Learn about lunar eclipses",
    url: "1.42-lunar-eclipse.html",
    category: "Events",
},
{
    id: "planetary-alignment",
    title: "Planetary Alignment",
    content: "When planets line up in the sky",
    url: "1.43-planetary-alignment.html",
    category: "Events",
},
{
    id: "meteor-shower",
    title: "Meteor Shower",
    content: "Learn about meteor showers",
    url: "1.44-meteor-shower.html",
    category: "Events",
},
{
    id: "iss-lookout",
    title: "Satellites Lookout",
    content: "Track the ISS and other satellites",
    url: "1.45-Iss-lookout.html",
    category: "Events",
},
{
    id: "astronomy-minds",
    title: "Great Minds in Astronomy",
    content: "Pioneers who advanced astronomy",
    url: "1.81-astronomy-great-minds.html",
    category: "Great Minds",
},
{
    id: "cosmology-minds",
    title: "Great Minds in Cosmology",
    content: "Scientists who shaped our view of the universe",
    url: "1.82-cosmology-great-minds.html",
    category: "Great Minds",
},
{
    id: "star-systems",
    title: "Near Earth Star Systems",
    content: "Explore star systems close to us",
    url: "2.2 Star-systems.html",
    category: "Fun Facts",
},
{
    id: "milky-map",
    title: "Milky Way Map",
    content: "Map of our home galaxy",
    url: "2.21 Milky Map.html",
    category: "Fun Facts",
},
{
    id: "centauri-system",
    title: "Centauri System",
    content: "Learn about our nearest stellar neighbor",
    url: "2.22 Centauri-system.html",
    category: "Fun Facts",
},
{
    id: "planets",
    title: "Planets",
    content: "Facts about planets in our solar system",
    url: "2.23 Planets.html",
    category: "Fun Facts",
},
{
    id: "constellations",
    title: "Constellations",
    content: "Learn about the patterns in the night sky",
    url: "2.01-Constellation.html",
    category: "Reference",
},
{
    id: "quiz",
    title: "Astronomy Quiz",
    content: "Test your astronomy knowledge",
    url: "2.0-quiz.html",
    category: "Interactive",
},
{
    id: "contact",
    title: "Contact",
    content: "Get in touch with us",
    url: "2.1-contact.html",
    category: "Main",
},
{
    id: "catalogs",
    title: "Astronomy Catalogs",
    content: "Messier, NGC, IC and other catalogs",
    url: "2.5-catalogs.html",
    category: "Reference",
},
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { searchIndex };
}
